import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Crimson_Text, Heebo, Archivo, Cardo } from "next/font/google";

const crimsonText = Crimson_Text({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});
const heebo = Heebo({
  subsets: ["latin"],
  variable: "--font-heebo",
  display: "swap",
});

const cardo = Cardo({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonText.className} ${cardo.className} ${heebo.variable} ${archivo.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
